#pragma once

#include "fold.h"
#include <algorithm>
#include <array>
#include <unordered_map>
#include <limits>
#include <cstdint>
#include <type_traits>

class ProfileNearestNeighbor;

#define HELIX_LENGTH

// State maps remain sparse and beam-bounded for every sequence length.  Pair
// candidates are generated by the LinearAlifold-style successor lists and
// position-dependent checks are memoized only when queried.

template < typename P, typename S = typename P::ScoreType >
class LinFold : public _Fold
{
    public:
        using ScoreType = S;

        struct Options : public _Fold::Options {;
            Options() : _Fold::Options(), beam_size_(100), alphabets_("acguACGU") {}

            Options& beam_size(u_int32_t s)
            {
                this->beam_size_ = s;
                return *this;
            }

            auto beam_size() const { return beam_size_; }
            // Mean nongap prefix counts for a profile; empty for one sequence.
            std::vector<double> occupancy_prefix_;
            float probability_cutoff_ = 0.01f;
            // Hashing successor queries is useful for larger profiles, but
            // is slower than the direct predicate for one or two rows.
            bool cache_position_pair_queries_ = true;
            // Populated only by two-row profile folding.  Codes are 0..35.
            std::vector<uint8_t> pair_signature_;
            // Present only if the alignment contains all-gap columns.  Such
            // columns cannot be the left endpoint of any profile pair.
            std::vector<u_int32_t> previous_occupied_;
            u_int32_t previous_candidate(u_int32_t column) const
            {
                return previous_occupied_.empty()
                    ? column : previous_occupied_[column];
            }
            double unpaired_span(u_int32_t left, u_int32_t right) const
            {
                return occupancy_prefix_.empty() ? right-left-1 :
                    occupancy_prefix_[right-1]-occupancy_prefix_[left];
            }
            bool allow_hairpin(u_int32_t left, u_int32_t right) const
            {
                return right-left>min_hairpin && (occupancy_prefix_.empty() ||
                    occupancy_prefix_[right]-occupancy_prefix_[left]>=2.0-1e-9);
            }
            Options& alphabets(std::string value) { alphabets_ = std::move(value); return *this; }
            u_int32_t next_valid_pair(
                const std::vector<std::vector<u_int32_t>>& next,
                const std::string& seq, u_int32_t left,
                u_int32_t after) const
            {
                const auto code = static_cast<unsigned char>(seq[left - 1]);
                if (next[code].empty()) return 0;
                auto right = next[code][after];
                while (right && position_pair_ && !position_pair_(left, right))
                    right = next[code][right];
                return right;
            }
            auto make_constraint(const std::string& seq, std::string alphabests=""s, bool canonical_only=true) const
                -> std::tuple<std::vector<std::vector<u_int32_t>>, std::vector<u_int32_t>, std::vector<bool>>;

            u_int32_t beam_size_;
            std::string alphabets_;
        };

    private:
        enum TBType
        {
            H_CLOSING,       // H -> [...]            ; hairpin candidate
                             // H -> [H ...]          ; extend hairpin candidate
#ifdef HELIX_LENGTH
            N_HAIRPIN_LOOP,  // N -> [ H ]            ; hairpin loop
            N_INTERNAL_LOOP, // N -> ( ... C ... )    ; single loop
            N_MULTI_LOOP,    // N -> [ M ]            ; multi loop
            E_HELIX,         // E -> ( E )            ; extended helix longer than max_helix_length
            E_TERMINAL,      // E -> N                ; terminal of extended helix
            C_TERMINAL,      // C -> N                ; isolated base-pair 
            C_HELIX,         // C -> ((( N )))        ; helix (< max_helix_length)
            C_HELIX_E,       // C -> ((( E )))        ; helix (= max_helix_length)
#else
            C_HAIRPIN_LOOP,  // C -> [ H ]            ; hairpin loop
            C_INTERNAL_LOOP, // C -> ( ... C ... )    ; single loop 
            C_MULTI_LOOP,    // C -> [ M ]            ; multi loop
#endif
            M_CLOSING,       // M -> ... M2 ...       ; multi loop candidate
                             // M -> M ...            ; extend multi loop candidate
            M2_BIFURCATION,  // M2 -> M1 C            ; add loop to multi loop candidate
            M1_M2,           // M1 -> M2              ; multi loop candidate without unpaired 
            M1_PAIRED,       // M1 -> C               ; right-most multi loop candidate
            M1_UNPAIRED,     // M1 -> M1 .            ; extend right-most multi loop candidate
            F_START,         // F -> empty            ; start external loop
            F_UNPAIRED,      // F -> F .              ; extend external loop
            F_BIFURCATION,   // F -> F C              ; add loop to external loop
            NONE
        };

        struct State
        {
            State() : score(std::numeric_limits<ScoreType>::lowest()), manner(NONE) {}
            State(ScoreType s, TBType t, u_int32_t k=0) : score(s), manner(t), ptr(k) {}  
            State(ScoreType s, TBType t, u_int16_t p, u_int16_t q) : score(s), manner(t), ptr(std::make_pair(p, q)) {}
            bool update_max(ScoreType s, TBType t, u_int32_t k=0);
            bool update_max(ScoreType s, TBType t, u_int16_t p, u_int16_t q);

            ScoreType score;
            TBType manner;
            std::variant<u_int32_t, std::pair<u_int16_t, u_int16_t>> ptr;
        };

        struct AlphaBeta
        {
            AlphaBeta() : alpha(-std::numeric_limits<ScoreType>::infinity()), beta(-std::numeric_limits<ScoreType>::infinity()) {}

            ScoreType alpha, beta;
        };

        static ScoreType beta_at(const std::unordered_map<u_int32_t, AlphaBeta>& states,
                                 u_int32_t i)
        {
            const auto found = states.find(i);
            return found == states.end() ? -std::numeric_limits<ScoreType>::infinity()
                                         : found->second.beta;
        }

    public:
        LinFold(std::unique_ptr<P>&& p);
        void reset_param_model(std::unique_ptr<P>&& p) { param_ = std::move(p); }
        auto compute_viterbi(const std::string& seq, const Options& opt = Options()) -> ScoreType;
        auto traceback_viterbi() -> std::vector<u_int32_t>;
        auto traceback_viterbi(const std::string& seq, const Options& opt = Options()) -> std::pair<typename P::ScoreType, std::vector<u_int32_t>>;
        auto compute_inside(const std::string& seq, const Options& opt = Options()) -> ScoreType;
        void compute_outside(const std::string& seq, const Options& opt = Options());
        auto compute_basepairing_probabilities(const std::string& seq, const Options& opt = Options()) -> std::vector<std::vector<std::pair<u_int32_t, float>>>;
        const P& param_model() const { return *param_; }

    private:
#ifdef HELIX_LENGTH
        void add_alpha_n(u_int32_t column, u_int32_t left, ScoreType score);

        ScoreType beta_at_n(u_int32_t column, u_int32_t left) const
        {
            return beta_at(Nio_[column], left);
        }
#endif
        bool allow_paired_cached(const Options& opts, const std::string& seq,
                                 u_int32_t i, u_int32_t j) const
        {
            return opts.allow_paired(seq, i, j);
        }
        ScoreType score_helix_extension(u_int32_t inner_i,
                                        u_int32_t inner_j, u_int32_t m)
        {
            if constexpr (std::is_same_v<P, ProfileNearestNeighbor>)
                return param_->score_helix_extend(
                    inner_i, inner_j, m, helix_scratch_);
            else
                return param_->score_helix(inner_i - (m - 1),
                                           inner_j + (m - 1), m);
        }
        void prepare_next_valid_lookup(
            const std::string& seq, const Options& opts,
            const std::vector<std::vector<u_int32_t>>& next_pair)
        {
            (void)next_pair;
            // Options and successor lists may change between inside,
            // outside, BPP, and Viterbi passes.  Keep only the sparse query
            // cache for the current pass.
            next_valid_cache_.clear();
            next_valid_cache_limit_ = opts.position_pair_ &&
                    opts.cache_position_pair_queries_
                ? std::max<size_t>(4096, seq.size() * 64) : 0;
            signature_next_valid_.clear();
            signature_first_.fill(0);
            if (opts.position_pair_ &&
                    opts.pair_signature_.size() == seq.size() + 1) {
                signature_next_valid_.resize(36);
                for (size_t column = 1; column <= seq.size(); ++column) {
                    const auto signature = opts.pair_signature_[column];
                    if (signature < signature_first_.size() &&
                            signature_first_[signature] == 0)
                        signature_first_[signature] = column;
                }
            }
        }
        u_int32_t next_valid_pair_cached(
            const Options& opts,
            const std::vector<std::vector<u_int32_t>>& next_pair,
            const std::string& seq, u_int32_t left, u_int32_t after) const
        {
            if (!signature_next_valid_.empty() && after >= left) {
                const auto signature = opts.pair_signature_[left];
                if (signature < signature_next_valid_.size()) {
                    auto& successors = signature_next_valid_[signature];
                    if (successors.empty()) {
                        successors.assign(seq.size() + 1, 0);
                        const auto first = signature_first_[signature];
                        const auto code = static_cast<unsigned char>(seq[first - 1]);
                        if (!next_pair[code].empty()) {
                            u_int32_t next = 0;
                            for (size_t position = seq.size(); position >= first;
                                 --position) {
                                successors[position] = next;
                                if (position > first &&
                                        next_pair[code][position - 1] == position &&
                                        opts.position_pair_(first, position))
                                    next = position;
                                if (position == first) break;
                            }
                        }
                    }
                    return successors[after];
                }
            }
            if (!opts.position_pair_ || !opts.cache_position_pair_queries_ ||
                    after < left)
                return opts.next_valid_pair(next_pair, seq, left, after);
            const auto key = (static_cast<uint64_t>(left) << 32) | after;
            const auto found = next_valid_cache_.find(key);
            if (found != next_valid_cache_.end()) return found->second;
            const auto next = opts.next_valid_pair(next_pair, seq, left, after);
            if (next_valid_cache_.size() < next_valid_cache_limit_)
                next_valid_cache_.emplace(key, next);
            return next;
        }
        auto beam_prune(std::unordered_map<u_int32_t, State>& state, u_int32_t beam_size) -> ScoreType;
        auto beam_prune(std::unordered_map<u_int32_t, AlphaBeta>& state, u_int32_t beam_size) -> ScoreType;

    private:
        std::unique_ptr<P> param_;
        // Reused by every beam pruning step, including profile folding.
        std::vector<std::pair<ScoreType, u_int32_t>> prune_scratch_;
        std::vector<double> helix_scratch_;
        mutable std::unordered_map<uint64_t, u_int32_t> next_valid_cache_;
        size_t next_valid_cache_limit_ = 0;
        std::array<u_int32_t, 36> signature_first_{};
        mutable std::vector<std::vector<u_int32_t>> signature_next_valid_;
#ifdef HELIX_LENGTH
        // N states are already stored in sparse maps.  A second triangular
        // pointer table would reintroduce quadratic memory.
#endif

        std::vector<std::unordered_map<u_int32_t, State>> Hv_, Cv_, Mv_, M1v_, M2v_;
#ifdef HELIX_LENGTH
        std::vector<std::unordered_map<u_int32_t, State>> Nv_, Ev_;
#endif
        std::vector<State> Fv_;

        std::vector<std::unordered_map<u_int32_t, AlphaBeta>> Hio_, Cio_, Mio_, M1io_, M2io_; 
#ifdef HELIX_LENGTH
        std::vector<std::unordered_map<u_int32_t, AlphaBeta>> Nio_, Eio_;
#endif
        std::vector<AlphaBeta> Fio_;
};
