#!/usr/bin/env python3
"""Package the rendered HTML slides into a legacy image-backed PPTX.

The editable deliverable is generated by ``export_dafs_editable_pptx.mjs``.
This helper remains only for reproducing the old screenshot-backed artifact and
therefore writes to an explicitly named legacy output.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from pptx import Presentation
from pptx.util import Inches


ROOT = Path(__file__).resolve().parent
RENDER_DIR = ROOT / "dafs_linearization_render"
OUTPUT = ROOT / "dafs_linearization_slides_imagebacked_legacy.pptx"


def slide_number(path: Path) -> int:
    match = re.search(r"slide-(\d+)\.png$", path.name)
    if match is None:
        raise ValueError(f"unexpected render filename: {path}")
    return int(match.group(1))


def main() -> int:
    images = sorted(RENDER_DIR.glob("slide-*.png"), key=slide_number)
    if len(images) != 12:
        raise SystemExit(f"expected 12 rendered slides, found {len(images)}")

    presentation = Presentation()
    presentation.slide_width = Inches(13.333)
    presentation.slide_height = Inches(7.5)
    blank_layout = presentation.slide_layouts[6]

    for image in images:
        slide = presentation.slides.add_slide(blank_layout)
        slide.shapes.add_picture(
            str(image), 0, 0,
            width=presentation.slide_width,
            height=presentation.slide_height,
        )

    presentation.save(OUTPUT)
    print(f"wrote {OUTPUT} ({len(images)} slides)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
