add_subdirectory(contrafold)
add_subdirectory(probconsRNA)
add_subdirectory(contralign)
add_subdirectory(linearfold)
add_subdirectory(linearalign)

# for building a statically linked binary
# set(CMAKE_FIND_LIBRARY_SUFFIXES .a ${CMAKE_FIND_LIBRARY_SUFFIXES})
# set(BUILD_SHARED_LIBRARIES OFF)
# set(CMAKE_EXE_LINKER_FLAGS "-static")

set(CMAKE_MODULE_PATH ${PROJECT_SOURCE_DIR}/cmake)

add_executable(
    dafs
    alifold.cpp align.cpp boltzmann_param.c dafs.cpp fa.cpp fold.cpp
    gradient_manager.cpp ip.cpp ipknot.cpp linfold_wrapper.cpp linearalign.cpp needleman_wunsch.cpp nussinov.cpp tree.cpp
)

target_compile_definitions(dafs PRIVATE PACKAGE="dafs")
target_compile_definitions(dafs PRIVATE PACKAGE_VERSION="0.0.4")
target_compile_definitions(dafs PRIVATE VERSION="0.0.4")
target_include_directories(dafs PRIVATE "spdlog/include")
target_include_directories(dafs PRIVATE "cxxopts/include")
target_compile_features(dafs PUBLIC cxx_std_17)

find_package(PkgConfig REQUIRED)
pkg_check_modules(VIENNARNA RNAlib2)
if (VIENNARNA_FOUND)
  target_include_directories(dafs PRIVATE ${VIENNARNA_INCLUDE_DIRS})
  target_compile_definitions(dafs PRIVATE HAVE_VIENNA18 HAVE_VIENNA20)
  target_link_libraries(dafs PRIVATE ${VIENNARNA_LDFLAGS} ${CMAKE_DL_LIBS})
endif()

if(ENABLE_CPLEX)
  find_package(CPLEX)
  if (CPLEX_FOUND)
    target_compile_definitions(dafs PRIVATE WITH_CPLEX)
    target_include_directories(dafs PRIVATE ${CPLEX_INCLUDE_DIR})
    target_link_libraries(dafs PRIVATE ${CPLEX_LIBRARY})
  endif()
elseif(ENABLE_GUROBI)
  find_package(GUROBI)
  if (GUROBI_FOUND)
    target_compile_definitions(dafs PRIVATE WITH_GUROBI)
    target_include_directories(dafs PRIVATE ${GUROBI_INCLUDE_DIR})
    target_link_libraries(dafs PRIVATE ${GUROBI_LIBRARY})
  endif()
elseif(ENABLE_SCIP)
  find_package(SCIP)
  if (SCIP_FOUND)
    message(STATUS "Found SCIP version ${SCIP_VERSION}")
    target_compile_definitions(dafs PRIVATE WITH_SCIP)
    target_include_directories(dafs PRIVATE ${SCIP_INCLUDE_DIRS})
    target_link_libraries(dafs PRIVATE ${SCIP_LIBRARIES})
  endif()
elseif(ENABLE_HIGHS)
  find_package(HiGHS)
  find_package(ZLIB 1.2.3)
  if (HiGHS_FOUND)
    target_compile_definitions(dafs PRIVATE WITH_HIGHS)
    target_include_directories(dafs PRIVATE ${HiGHS_INCLUDE_DIR})
    target_link_libraries(dafs PRIVATE ${HiGHS_LIBRARY} ${ZLIB_LIBRARY})
  endif()
else()
  find_package(GLPK)
  if (GLPK_FOUND)
    target_compile_definitions(dafs PRIVATE WITH_GLPK)
    target_include_directories(dafs PRIVATE ${GLPK_INCLUDE_DIR})
    target_link_libraries(dafs PRIVATE ${GLPK_LIBRARY} ${ZLIB_LIBRARY} ${GMP_LIBRARY} ${DL_LIBRARY} ${LTDL_LIBRARY} ${MPFR_LIBRARY})
  endif()
endif()

target_link_libraries(dafs PRIVATE contrafold probcons contralign linearfold linearalign)

install(TARGETS dafs RUNTIME DESTINATION bin)