/*
  File autogenerated by gengetopt version 2.22.4
  generated with the following command:
  gengetopt --unamed-opts 

  The developers of gengetopt consider the fixed text that goes in all
  gengetopt output files to be in the public domain:
  we make no copyright claims on it.
*/

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifndef FIX_UNUSED
#define FIX_UNUSED(X) (void) (X) /* avoid warnings for unused params */
#endif

#include <getopt.h>

#include "cmdline.h"

const char *gengetopt_args_info_purpose = "DUSAF: dual decomposition for simultaneous aligning and folding RNA sequences.";

const char *gengetopt_args_info_usage = "Usage: " CMDLINE_PARSER_PACKAGE " [OPTIONS]... [FILES]...";

const char *gengetopt_args_info_description = "";

const char *gengetopt_args_info_full_help[] = {
  "  -h, --help                Print help and exit",
  "      --full-help           Print help, including hidden options, and exit",
  "  -V, --version             Print version and exit",
  "  -r, --refinement=INT      The number of iteration of the iterative refinment  \n                              (default=`0')",
  "  -w, --weight=FLOAT        Weight of the expected accuracy score for secondary \n                              structures  (default=`1.0')",
  "      --eta=FLOAT           Initial step width for the subgradient optimization \n                               (default=`0.5')",
  "  -m, --max-iter=INT        The maximum number of iteration of the subgradient \n                              optimization  (default=`100')",
  "  -f, --fourway-pct=FLOAT   Weight of four-way PCT  (default=`0.0')",
  "  -v, --verbose=INT         The level of verbose outputs  (default=`0')",
  "\nOptions for alignments:",
  "  -a, --align-model=STRING  Alignment model for calcualating matching \n                              probablities  (possible values=\"CONTRAlign\", \n                              \"ProbCons\", \"PartAlign\" default=`CONTRAlign')",
  "  -p, --align-pct=FLOAT     Weight of PCT for matching probabilities  \n                              (default=`0.0')",
  "  -u, --align-th=FLOAT      Threshold for matching probabilities  \n                              (default=`0.01')",
  "      --use-bpscore         Use BP score  (default=on)",
  "      --extra=STRING        Extra options for PartAlign",
  "\nOptions for folding:",
  "  -s, --fold-model=STRING   Folding model for calculating base-pairing \n                              probablities  (possible values=\"Boltzmann\", \n                              \"Vienna\", \"CONTRAfold\" default=`Boltzmann')",
  "  -q, --fold-pct=FLOAT      Weight of PCT for base-pairing probabilities  \n                              (default=`0.0')",
  "  -t, --fold-th=FLOAT       Threshold for base-pairing probabilities  \n                              (default=`0.2')",
  "  -g, --gamma=FLOAT         Specify the threshold for base-pairing \n                              probabilities by 1/(gamma+1))",
  "  -l, --use-alifold         Use RNAalifold for calculating base-pairing \n                              probabilities  (default=off)",
    0
};

static void
init_help_array(void)
{
  gengetopt_args_info_help[0] = gengetopt_args_info_full_help[0];
  gengetopt_args_info_help[1] = gengetopt_args_info_full_help[1];
  gengetopt_args_info_help[2] = gengetopt_args_info_full_help[2];
  gengetopt_args_info_help[3] = gengetopt_args_info_full_help[3];
  gengetopt_args_info_help[4] = gengetopt_args_info_full_help[4];
  gengetopt_args_info_help[5] = gengetopt_args_info_full_help[5];
  gengetopt_args_info_help[6] = gengetopt_args_info_full_help[6];
  gengetopt_args_info_help[7] = gengetopt_args_info_full_help[7];
  gengetopt_args_info_help[8] = gengetopt_args_info_full_help[8];
  gengetopt_args_info_help[9] = gengetopt_args_info_full_help[9];
  gengetopt_args_info_help[10] = gengetopt_args_info_full_help[10];
  gengetopt_args_info_help[11] = gengetopt_args_info_full_help[11];
  gengetopt_args_info_help[12] = gengetopt_args_info_full_help[12];
  gengetopt_args_info_help[13] = gengetopt_args_info_full_help[15];
  gengetopt_args_info_help[14] = gengetopt_args_info_full_help[16];
  gengetopt_args_info_help[15] = gengetopt_args_info_full_help[17];
  gengetopt_args_info_help[16] = gengetopt_args_info_full_help[18];
  gengetopt_args_info_help[17] = gengetopt_args_info_full_help[20];
  gengetopt_args_info_help[18] = 0; 
  
}

const char *gengetopt_args_info_help[19];

typedef enum {ARG_NO
  , ARG_FLAG
  , ARG_STRING
  , ARG_INT
  , ARG_FLOAT
} cmdline_parser_arg_type;

static
void clear_given (struct gengetopt_args_info *args_info);
static
void clear_args (struct gengetopt_args_info *args_info);

static int
cmdline_parser_internal (int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error);


const char *cmdline_parser_align_model_values[] = {"CONTRAlign", "ProbCons", "PartAlign", 0}; /*< Possible values for align-model. */
const char *cmdline_parser_fold_model_values[] = {"Boltzmann", "Vienna", "CONTRAfold", 0}; /*< Possible values for fold-model. */

static char *
gengetopt_strdup (const char *s);

static
void clear_given (struct gengetopt_args_info *args_info)
{
  args_info->help_given = 0 ;
  args_info->full_help_given = 0 ;
  args_info->version_given = 0 ;
  args_info->refinement_given = 0 ;
  args_info->weight_given = 0 ;
  args_info->eta_given = 0 ;
  args_info->max_iter_given = 0 ;
  args_info->fourway_pct_given = 0 ;
  args_info->verbose_given = 0 ;
  args_info->align_model_given = 0 ;
  args_info->align_pct_given = 0 ;
  args_info->align_th_given = 0 ;
  args_info->use_bpscore_given = 0 ;
  args_info->extra_given = 0 ;
  args_info->fold_model_given = 0 ;
  args_info->fold_pct_given = 0 ;
  args_info->fold_th_given = 0 ;
  args_info->gamma_given = 0 ;
  args_info->use_alifold_given = 0 ;
}

static
void clear_args (struct gengetopt_args_info *args_info)
{
  FIX_UNUSED (args_info);
  args_info->refinement_arg = 0;
  args_info->refinement_orig = NULL;
  args_info->weight_arg = 1.0;
  args_info->weight_orig = NULL;
  args_info->eta_arg = 0.5;
  args_info->eta_orig = NULL;
  args_info->max_iter_arg = 100;
  args_info->max_iter_orig = NULL;
  args_info->fourway_pct_arg = 0.0;
  args_info->fourway_pct_orig = NULL;
  args_info->verbose_arg = 0;
  args_info->verbose_orig = NULL;
  args_info->align_model_arg = gengetopt_strdup ("CONTRAlign");
  args_info->align_model_orig = NULL;
  args_info->align_pct_arg = 0.0;
  args_info->align_pct_orig = NULL;
  args_info->align_th_arg = 0.01;
  args_info->align_th_orig = NULL;
  args_info->use_bpscore_flag = 1;
  args_info->extra_arg = NULL;
  args_info->extra_orig = NULL;
  args_info->fold_model_arg = gengetopt_strdup ("Boltzmann");
  args_info->fold_model_orig = NULL;
  args_info->fold_pct_arg = 0.0;
  args_info->fold_pct_orig = NULL;
  args_info->fold_th_arg = 0.2;
  args_info->fold_th_orig = NULL;
  args_info->gamma_orig = NULL;
  args_info->use_alifold_flag = 0;
  
}

static
void init_args_info(struct gengetopt_args_info *args_info)
{

  init_help_array(); 
  args_info->help_help = gengetopt_args_info_full_help[0] ;
  args_info->full_help_help = gengetopt_args_info_full_help[1] ;
  args_info->version_help = gengetopt_args_info_full_help[2] ;
  args_info->refinement_help = gengetopt_args_info_full_help[3] ;
  args_info->weight_help = gengetopt_args_info_full_help[4] ;
  args_info->eta_help = gengetopt_args_info_full_help[5] ;
  args_info->max_iter_help = gengetopt_args_info_full_help[6] ;
  args_info->fourway_pct_help = gengetopt_args_info_full_help[7] ;
  args_info->verbose_help = gengetopt_args_info_full_help[8] ;
  args_info->align_model_help = gengetopt_args_info_full_help[10] ;
  args_info->align_pct_help = gengetopt_args_info_full_help[11] ;
  args_info->align_th_help = gengetopt_args_info_full_help[12] ;
  args_info->use_bpscore_help = gengetopt_args_info_full_help[13] ;
  args_info->extra_help = gengetopt_args_info_full_help[14] ;
  args_info->fold_model_help = gengetopt_args_info_full_help[16] ;
  args_info->fold_pct_help = gengetopt_args_info_full_help[17] ;
  args_info->fold_th_help = gengetopt_args_info_full_help[18] ;
  args_info->gamma_help = gengetopt_args_info_full_help[19] ;
  args_info->use_alifold_help = gengetopt_args_info_full_help[20] ;
  
}

void
cmdline_parser_print_version (void)
{
  printf ("%s %s\n",
     (strlen(CMDLINE_PARSER_PACKAGE_NAME) ? CMDLINE_PARSER_PACKAGE_NAME : CMDLINE_PARSER_PACKAGE),
     CMDLINE_PARSER_VERSION);
}

static void print_help_common(void) {
  cmdline_parser_print_version ();

  if (strlen(gengetopt_args_info_purpose) > 0)
    printf("\n%s\n", gengetopt_args_info_purpose);

  if (strlen(gengetopt_args_info_usage) > 0)
    printf("\n%s\n", gengetopt_args_info_usage);

  printf("\n");

  if (strlen(gengetopt_args_info_description) > 0)
    printf("%s\n\n", gengetopt_args_info_description);
}

void
cmdline_parser_print_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_help[i])
    printf("%s\n", gengetopt_args_info_help[i++]);
}

void
cmdline_parser_print_full_help (void)
{
  int i = 0;
  print_help_common();
  while (gengetopt_args_info_full_help[i])
    printf("%s\n", gengetopt_args_info_full_help[i++]);
}

void
cmdline_parser_init (struct gengetopt_args_info *args_info)
{
  clear_given (args_info);
  clear_args (args_info);
  init_args_info (args_info);

  args_info->inputs = 0;
  args_info->inputs_num = 0;
}

void
cmdline_parser_params_init(struct cmdline_parser_params *params)
{
  if (params)
    { 
      params->override = 0;
      params->initialize = 1;
      params->check_required = 1;
      params->check_ambiguity = 0;
      params->print_errors = 1;
    }
}

struct cmdline_parser_params *
cmdline_parser_params_create(void)
{
  struct cmdline_parser_params *params = 
    (struct cmdline_parser_params *)malloc(sizeof(struct cmdline_parser_params));
  cmdline_parser_params_init(params);  
  return params;
}

static void
free_string_field (char **s)
{
  if (*s)
    {
      free (*s);
      *s = 0;
    }
}


static void
cmdline_parser_release (struct gengetopt_args_info *args_info)
{
  unsigned int i;
  free_string_field (&(args_info->refinement_orig));
  free_string_field (&(args_info->weight_orig));
  free_string_field (&(args_info->eta_orig));
  free_string_field (&(args_info->max_iter_orig));
  free_string_field (&(args_info->fourway_pct_orig));
  free_string_field (&(args_info->verbose_orig));
  free_string_field (&(args_info->align_model_arg));
  free_string_field (&(args_info->align_model_orig));
  free_string_field (&(args_info->align_pct_orig));
  free_string_field (&(args_info->align_th_orig));
  free_string_field (&(args_info->extra_arg));
  free_string_field (&(args_info->extra_orig));
  free_string_field (&(args_info->fold_model_arg));
  free_string_field (&(args_info->fold_model_orig));
  free_string_field (&(args_info->fold_pct_orig));
  free_string_field (&(args_info->fold_th_orig));
  free_string_field (&(args_info->gamma_orig));
  
  
  for (i = 0; i < args_info->inputs_num; ++i)
    free (args_info->inputs [i]);

  if (args_info->inputs_num)
    free (args_info->inputs);

  clear_given (args_info);
}

/**
 * @param val the value to check
 * @param values the possible values
 * @return the index of the matched value:
 * -1 if no value matched,
 * -2 if more than one value has matched
 */
static int
check_possible_values(const char *val, const char *values[])
{
  int i, found, last;
  size_t len;

  if (!val)   /* otherwise strlen() crashes below */
    return -1; /* -1 means no argument for the option */

  found = last = 0;

  for (i = 0, len = strlen(val); values[i]; ++i)
    {
      if (strncmp(val, values[i], len) == 0)
        {
          ++found;
          last = i;
          if (strlen(values[i]) == len)
            return i; /* exact macth no need to check more */
        }
    }

  if (found == 1) /* one match: OK */
    return last;

  return (found ? -2 : -1); /* return many values or none matched */
}


static void
write_into_file(FILE *outfile, const char *opt, const char *arg, const char *values[])
{
  int found = -1;
  if (arg) {
    if (values) {
      found = check_possible_values(arg, values);      
    }
    if (found >= 0)
      fprintf(outfile, "%s=\"%s\" # %s\n", opt, arg, values[found]);
    else
      fprintf(outfile, "%s=\"%s\"\n", opt, arg);
  } else {
    fprintf(outfile, "%s\n", opt);
  }
}


int
cmdline_parser_dump(FILE *outfile, struct gengetopt_args_info *args_info)
{
  int i = 0;

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot dump options to stream\n", CMDLINE_PARSER_PACKAGE);
      return EXIT_FAILURE;
    }

  if (args_info->help_given)
    write_into_file(outfile, "help", 0, 0 );
  if (args_info->full_help_given)
    write_into_file(outfile, "full-help", 0, 0 );
  if (args_info->version_given)
    write_into_file(outfile, "version", 0, 0 );
  if (args_info->refinement_given)
    write_into_file(outfile, "refinement", args_info->refinement_orig, 0);
  if (args_info->weight_given)
    write_into_file(outfile, "weight", args_info->weight_orig, 0);
  if (args_info->eta_given)
    write_into_file(outfile, "eta", args_info->eta_orig, 0);
  if (args_info->max_iter_given)
    write_into_file(outfile, "max-iter", args_info->max_iter_orig, 0);
  if (args_info->fourway_pct_given)
    write_into_file(outfile, "fourway-pct", args_info->fourway_pct_orig, 0);
  if (args_info->verbose_given)
    write_into_file(outfile, "verbose", args_info->verbose_orig, 0);
  if (args_info->align_model_given)
    write_into_file(outfile, "align-model", args_info->align_model_orig, cmdline_parser_align_model_values);
  if (args_info->align_pct_given)
    write_into_file(outfile, "align-pct", args_info->align_pct_orig, 0);
  if (args_info->align_th_given)
    write_into_file(outfile, "align-th", args_info->align_th_orig, 0);
  if (args_info->use_bpscore_given)
    write_into_file(outfile, "use-bpscore", 0, 0 );
  if (args_info->extra_given)
    write_into_file(outfile, "extra", args_info->extra_orig, 0);
  if (args_info->fold_model_given)
    write_into_file(outfile, "fold-model", args_info->fold_model_orig, cmdline_parser_fold_model_values);
  if (args_info->fold_pct_given)
    write_into_file(outfile, "fold-pct", args_info->fold_pct_orig, 0);
  if (args_info->fold_th_given)
    write_into_file(outfile, "fold-th", args_info->fold_th_orig, 0);
  if (args_info->gamma_given)
    write_into_file(outfile, "gamma", args_info->gamma_orig, 0);
  if (args_info->use_alifold_given)
    write_into_file(outfile, "use-alifold", 0, 0 );
  

  i = EXIT_SUCCESS;
  return i;
}

int
cmdline_parser_file_save(const char *filename, struct gengetopt_args_info *args_info)
{
  FILE *outfile;
  int i = 0;

  outfile = fopen(filename, "w");

  if (!outfile)
    {
      fprintf (stderr, "%s: cannot open file for writing: %s\n", CMDLINE_PARSER_PACKAGE, filename);
      return EXIT_FAILURE;
    }

  i = cmdline_parser_dump(outfile, args_info);
  fclose (outfile);

  return i;
}

void
cmdline_parser_free (struct gengetopt_args_info *args_info)
{
  cmdline_parser_release (args_info);
}

/** @brief replacement of strdup, which is not standard */
char *
gengetopt_strdup (const char *s)
{
  char *result = 0;
  if (!s)
    return result;

  result = (char*)malloc(strlen(s) + 1);
  if (result == (char*)0)
    return (char*)0;
  strcpy(result, s);
  return result;
}

int
cmdline_parser (int argc, char **argv, struct gengetopt_args_info *args_info)
{
  return cmdline_parser2 (argc, argv, args_info, 0, 1, 1);
}

int
cmdline_parser_ext (int argc, char **argv, struct gengetopt_args_info *args_info,
                   struct cmdline_parser_params *params)
{
  int result;
  result = cmdline_parser_internal (argc, argv, args_info, params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser2 (int argc, char **argv, struct gengetopt_args_info *args_info, int override, int initialize, int check_required)
{
  int result;
  struct cmdline_parser_params params;
  
  params.override = override;
  params.initialize = initialize;
  params.check_required = check_required;
  params.check_ambiguity = 0;
  params.print_errors = 1;

  result = cmdline_parser_internal (argc, argv, args_info, &params, 0);

  if (result == EXIT_FAILURE)
    {
      cmdline_parser_free (args_info);
      exit (EXIT_FAILURE);
    }
  
  return result;
}

int
cmdline_parser_required (struct gengetopt_args_info *args_info, const char *prog_name)
{
  FIX_UNUSED (args_info);
  FIX_UNUSED (prog_name);
  return EXIT_SUCCESS;
}


static char *package_name = 0;

/**
 * @brief updates an option
 * @param field the generic pointer to the field to update
 * @param orig_field the pointer to the orig field
 * @param field_given the pointer to the number of occurrence of this option
 * @param prev_given the pointer to the number of occurrence already seen
 * @param value the argument for this option (if null no arg was specified)
 * @param possible_values the possible values for this option (if specified)
 * @param default_value the default value (in case the option only accepts fixed values)
 * @param arg_type the type of this option
 * @param check_ambiguity @see cmdline_parser_params.check_ambiguity
 * @param override @see cmdline_parser_params.override
 * @param no_free whether to free a possible previous value
 * @param multiple_option whether this is a multiple option
 * @param long_opt the corresponding long option
 * @param short_opt the corresponding short option (or '-' if none)
 * @param additional_error possible further error specification
 */
static
int update_arg(void *field, char **orig_field,
               unsigned int *field_given, unsigned int *prev_given, 
               char *value, const char *possible_values[],
               const char *default_value,
               cmdline_parser_arg_type arg_type,
               int check_ambiguity, int override,
               int no_free, int multiple_option,
               const char *long_opt, char short_opt,
               const char *additional_error)
{
  char *stop_char = 0;
  const char *val = value;
  int found;
  char **string_field;
  FIX_UNUSED (field);

  stop_char = 0;
  found = 0;

  if (!multiple_option && prev_given && (*prev_given || (check_ambiguity && *field_given)))
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: `--%s' (`-%c') option given more than once%s\n", 
               package_name, long_opt, short_opt,
               (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: `--%s' option given more than once%s\n", 
               package_name, long_opt,
               (additional_error ? additional_error : ""));
      return 1; /* failure */
    }

  if (possible_values && (found = check_possible_values((value ? value : default_value), possible_values)) < 0)
    {
      if (short_opt != '-')
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s' (`-%c')%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt, short_opt,
          (additional_error ? additional_error : ""));
      else
        fprintf (stderr, "%s: %s argument, \"%s\", for option `--%s'%s\n", 
          package_name, (found == -2) ? "ambiguous" : "invalid", value, long_opt,
          (additional_error ? additional_error : ""));
      return 1; /* failure */
    }
    
  if (field_given && *field_given && ! override)
    return 0;
  if (prev_given)
    (*prev_given)++;
  if (field_given)
    (*field_given)++;
  if (possible_values)
    val = possible_values[found];

  switch(arg_type) {
  case ARG_FLAG:
    *((int *)field) = !*((int *)field);
    break;
  case ARG_INT:
    if (val) *((int *)field) = strtol (val, &stop_char, 0);
    break;
  case ARG_FLOAT:
    if (val) *((float *)field) = (float)strtod (val, &stop_char);
    break;
  case ARG_STRING:
    if (val) {
      string_field = (char **)field;
      if (!no_free && *string_field)
        free (*string_field); /* free previous string */
      *string_field = gengetopt_strdup (val);
    }
    break;
  default:
    break;
  };

  /* check numeric conversion */
  switch(arg_type) {
  case ARG_INT:
  case ARG_FLOAT:
    if (val && !(stop_char && *stop_char == '\0')) {
      fprintf(stderr, "%s: invalid numeric value: %s\n", package_name, val);
      return 1; /* failure */
    }
    break;
  default:
    ;
  };

  /* store the original value */
  switch(arg_type) {
  case ARG_NO:
  case ARG_FLAG:
    break;
  default:
    if (value && orig_field) {
      if (no_free) {
        *orig_field = value;
      } else {
        if (*orig_field)
          free (*orig_field); /* free previous string */
        *orig_field = gengetopt_strdup (value);
      }
    }
  };

  return 0; /* OK */
}


int
cmdline_parser_internal (
  int argc, char **argv, struct gengetopt_args_info *args_info,
                        struct cmdline_parser_params *params, const char *additional_error)
{
  int c;	/* Character of the parsed option.  */

  int error = 0;
  struct gengetopt_args_info local_args_info;
  
  int override;
  int initialize;
  int check_required;
  int check_ambiguity;
  
  package_name = argv[0];
  
  override = params->override;
  initialize = params->initialize;
  check_required = params->check_required;
  check_ambiguity = params->check_ambiguity;

  if (initialize)
    cmdline_parser_init (args_info);

  cmdline_parser_init (&local_args_info);

  optarg = 0;
  optind = 0;
  opterr = params->print_errors;
  optopt = '?';

  while (1)
    {
      int option_index = 0;

      static struct option long_options[] = {
        { "help",	0, NULL, 'h' },
        { "full-help",	0, NULL, 0 },
        { "version",	0, NULL, 'V' },
        { "refinement",	1, NULL, 'r' },
        { "weight",	1, NULL, 'w' },
        { "eta",	1, NULL, 0 },
        { "max-iter",	1, NULL, 'm' },
        { "fourway-pct",	1, NULL, 'f' },
        { "verbose",	1, NULL, 'v' },
        { "align-model",	1, NULL, 'a' },
        { "align-pct",	1, NULL, 'p' },
        { "align-th",	1, NULL, 'u' },
        { "use-bpscore",	0, NULL, 0 },
        { "extra",	1, NULL, 0 },
        { "fold-model",	1, NULL, 's' },
        { "fold-pct",	1, NULL, 'q' },
        { "fold-th",	1, NULL, 't' },
        { "gamma",	1, NULL, 'g' },
        { "use-alifold",	0, NULL, 'l' },
        { 0,  0, 0, 0 }
      };

      c = getopt_long (argc, argv, "hVr:w:m:f:v:a:p:u:s:q:t:g:l", long_options, &option_index);

      if (c == -1) break;	/* Exit from `while (1)' loop.  */

      switch (c)
        {
        case 'h':	/* Print help and exit.  */
          cmdline_parser_print_help ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'V':	/* Print version and exit.  */
          cmdline_parser_print_version ();
          cmdline_parser_free (&local_args_info);
          exit (EXIT_SUCCESS);

        case 'r':	/* The number of iteration of the iterative refinment.  */
        
        
          if (update_arg( (void *)&(args_info->refinement_arg), 
               &(args_info->refinement_orig), &(args_info->refinement_given),
              &(local_args_info.refinement_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "refinement", 'r',
              additional_error))
            goto failure;
        
          break;
        case 'w':	/* Weight of the expected accuracy score for secondary structures.  */
        
        
          if (update_arg( (void *)&(args_info->weight_arg), 
               &(args_info->weight_orig), &(args_info->weight_given),
              &(local_args_info.weight_given), optarg, 0, "1.0", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "weight", 'w',
              additional_error))
            goto failure;
        
          break;
        case 'm':	/* The maximum number of iteration of the subgradient optimization.  */
        
        
          if (update_arg( (void *)&(args_info->max_iter_arg), 
               &(args_info->max_iter_orig), &(args_info->max_iter_given),
              &(local_args_info.max_iter_given), optarg, 0, "100", ARG_INT,
              check_ambiguity, override, 0, 0,
              "max-iter", 'm',
              additional_error))
            goto failure;
        
          break;
        case 'f':	/* Weight of four-way PCT.  */
        
        
          if (update_arg( (void *)&(args_info->fourway_pct_arg), 
               &(args_info->fourway_pct_orig), &(args_info->fourway_pct_given),
              &(local_args_info.fourway_pct_given), optarg, 0, "0.0", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "fourway-pct", 'f',
              additional_error))
            goto failure;
        
          break;
        case 'v':	/* The level of verbose outputs.  */
        
        
          if (update_arg( (void *)&(args_info->verbose_arg), 
               &(args_info->verbose_orig), &(args_info->verbose_given),
              &(local_args_info.verbose_given), optarg, 0, "0", ARG_INT,
              check_ambiguity, override, 0, 0,
              "verbose", 'v',
              additional_error))
            goto failure;
        
          break;
        case 'a':	/* Alignment model for calcualating matching probablities.  */
        
        
          if (update_arg( (void *)&(args_info->align_model_arg), 
               &(args_info->align_model_orig), &(args_info->align_model_given),
              &(local_args_info.align_model_given), optarg, cmdline_parser_align_model_values, "CONTRAlign", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "align-model", 'a',
              additional_error))
            goto failure;
        
          break;
        case 'p':	/* Weight of PCT for matching probabilities.  */
        
        
          if (update_arg( (void *)&(args_info->align_pct_arg), 
               &(args_info->align_pct_orig), &(args_info->align_pct_given),
              &(local_args_info.align_pct_given), optarg, 0, "0.0", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "align-pct", 'p',
              additional_error))
            goto failure;
        
          break;
        case 'u':	/* Threshold for matching probabilities.  */
        
        
          if (update_arg( (void *)&(args_info->align_th_arg), 
               &(args_info->align_th_orig), &(args_info->align_th_given),
              &(local_args_info.align_th_given), optarg, 0, "0.01", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "align-th", 'u',
              additional_error))
            goto failure;
        
          break;
        case 's':	/* Folding model for calculating base-pairing probablities.  */
        
        
          if (update_arg( (void *)&(args_info->fold_model_arg), 
               &(args_info->fold_model_orig), &(args_info->fold_model_given),
              &(local_args_info.fold_model_given), optarg, cmdline_parser_fold_model_values, "Boltzmann", ARG_STRING,
              check_ambiguity, override, 0, 0,
              "fold-model", 's',
              additional_error))
            goto failure;
        
          break;
        case 'q':	/* Weight of PCT for base-pairing probabilities.  */
        
        
          if (update_arg( (void *)&(args_info->fold_pct_arg), 
               &(args_info->fold_pct_orig), &(args_info->fold_pct_given),
              &(local_args_info.fold_pct_given), optarg, 0, "0.0", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "fold-pct", 'q',
              additional_error))
            goto failure;
        
          break;
        case 't':	/* Threshold for base-pairing probabilities.  */
        
        
          if (update_arg( (void *)&(args_info->fold_th_arg), 
               &(args_info->fold_th_orig), &(args_info->fold_th_given),
              &(local_args_info.fold_th_given), optarg, 0, "0.2", ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "fold-th", 't',
              additional_error))
            goto failure;
        
          break;
        case 'g':	/* Specify the threshold for base-pairing probabilities by 1/(gamma+1)).  */
        
        
          if (update_arg( (void *)&(args_info->gamma_arg), 
               &(args_info->gamma_orig), &(args_info->gamma_given),
              &(local_args_info.gamma_given), optarg, 0, 0, ARG_FLOAT,
              check_ambiguity, override, 0, 0,
              "gamma", 'g',
              additional_error))
            goto failure;
        
          break;
        case 'l':	/* Use RNAalifold for calculating base-pairing probabilities.  */
        
        
          if (update_arg((void *)&(args_info->use_alifold_flag), 0, &(args_info->use_alifold_given),
              &(local_args_info.use_alifold_given), optarg, 0, 0, ARG_FLAG,
              check_ambiguity, override, 1, 0, "use-alifold", 'l',
              additional_error))
            goto failure;
        
          break;

        case 0:	/* Long option with no short option */
          if (strcmp (long_options[option_index].name, "full-help") == 0) {
            cmdline_parser_print_full_help ();
            cmdline_parser_free (&local_args_info);
            exit (EXIT_SUCCESS);
          }

          /* Initial step width for the subgradient optimization.  */
          if (strcmp (long_options[option_index].name, "eta") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->eta_arg), 
                 &(args_info->eta_orig), &(args_info->eta_given),
                &(local_args_info.eta_given), optarg, 0, "0.5", ARG_FLOAT,
                check_ambiguity, override, 0, 0,
                "eta", '-',
                additional_error))
              goto failure;
          
          }
          /* Use BP score.  */
          else if (strcmp (long_options[option_index].name, "use-bpscore") == 0)
          {
          
          
            if (update_arg((void *)&(args_info->use_bpscore_flag), 0, &(args_info->use_bpscore_given),
                &(local_args_info.use_bpscore_given), optarg, 0, 0, ARG_FLAG,
                check_ambiguity, override, 1, 0, "use-bpscore", '-',
                additional_error))
              goto failure;
          
          }
          /* Extra options for PartAlign.  */
          else if (strcmp (long_options[option_index].name, "extra") == 0)
          {
          
          
            if (update_arg( (void *)&(args_info->extra_arg), 
                 &(args_info->extra_orig), &(args_info->extra_given),
                &(local_args_info.extra_given), optarg, 0, 0, ARG_STRING,
                check_ambiguity, override, 0, 0,
                "extra", '-',
                additional_error))
              goto failure;
          
          }
          
          break;
        case '?':	/* Invalid option.  */
          /* `getopt_long' already printed an error message.  */
          goto failure;

        default:	/* bug: option not considered.  */
          fprintf (stderr, "%s: option unknown: %c%s\n", CMDLINE_PARSER_PACKAGE, c, (additional_error ? additional_error : ""));
          abort ();
        } /* switch */
    } /* while */




  cmdline_parser_release (&local_args_info);

  if ( error )
    return (EXIT_FAILURE);

  if (optind < argc)
    {
      int i = 0 ;
      int found_prog_name = 0;
      /* whether program name, i.e., argv[0], is in the remaining args
         (this may happen with some implementations of getopt,
          but surely not with the one included by gengetopt) */

      i = optind;
      while (i < argc)
        if (argv[i++] == argv[0]) {
          found_prog_name = 1;
          break;
        }
      i = 0;

      args_info->inputs_num = argc - optind - found_prog_name;
      args_info->inputs =
        (char **)(malloc ((args_info->inputs_num)*sizeof(char *))) ;
      while (optind < argc)
        if (argv[optind++] != argv[0])
          args_info->inputs[ i++ ] = gengetopt_strdup (argv[optind-1]) ;
    }

  return 0;

failure:
  
  cmdline_parser_release (&local_args_info);
  return (EXIT_FAILURE);
}
